import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, CheckCircle2, Download, ExternalLink, FileText, Plus, Send, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { applicationApi, internshipApi, materialApi, skillGapApi } from "../api/queries";
import { Button } from "../components/Button";
import { ErrorBanner } from "../components/ErrorBanner";
import { LoadingState } from "../components/LoadingState";
import { formatDate } from "../utils/format";

export function InternshipDetails() {
  const { id } = useParams();
  const queryClient = useQueryClient();
  const [generatedVersion, setGeneratedVersion] = useState(null);
  const [applicationNotice, setApplicationNotice] = useState("");
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfError, setPdfError] = useState("");
  const internshipsQuery = useQuery({ queryKey: ["internships"], queryFn: internshipApi.list });
  const resumeVersionsQuery = useQuery({ queryKey: ["resume-versions"], queryFn: materialApi.list });
  const internship = useMemo(
    () => internshipsQuery.data?.internships?.find((item) => String(item._id) === String(id)),
    [internshipsQuery.data, id]
  );
  const existingVersion = useMemo(
    () =>
      resumeVersionsQuery.data?.resumeVersions?.find(
        (version) => String(version.internshipId) === String(id)
      ),
    [resumeVersionsQuery.data, id]
  );
  const resumeVersion = generatedVersion || existingVersion;
  const skillGapQuery = useQuery({
    queryKey: ["skill-gap", id],
    queryFn: () => skillGapApi.get(id),
    enabled: Boolean(internship?.match)
  });
  const materialMutation = useMutation({
    mutationFn: materialApi.generate,
    onSuccess: (data) => {
      setGeneratedVersion(data.resumeVersion);
      setApplicationNotice("Resume version generated and Tracker moved to Preparing.");
      queryClient.invalidateQueries({ queryKey: ["resume-versions"] });
      queryClient.invalidateQueries({ queryKey: ["applications"] });
      queryClient.invalidateQueries({ queryKey: ["analytics"] });
    }
  });
  const approveMutation = useMutation({
    mutationFn: materialApi.approve,
    onSuccess: (data) => {
      setGeneratedVersion(data.resumeVersion);
      queryClient.invalidateQueries({ queryKey: ["resume-versions"] });
    }
  });
  const applicationMutation = useMutation({
    mutationFn: applicationApi.create,
    onSuccess: () => {
      setApplicationNotice("Saved to Tracker.");
      queryClient.invalidateQueries({ queryKey: ["applications"] });
      queryClient.invalidateQueries({ queryKey: ["analytics"] });
      queryClient.invalidateQueries({ queryKey: ["notifications"] });
    }
  });
  const externalApplyMutation = useMutation({
    mutationFn: () => applicationApi.create({ internshipId: internship._id, status: "APPLIED" }),
    onSuccess: () => {
      setApplicationNotice("Applied externally and saved to Tracker.");
      queryClient.invalidateQueries({ queryKey: ["applications"] });
      queryClient.invalidateQueries({ queryKey: ["analytics"] });
      queryClient.invalidateQueries({ queryKey: ["notifications"] });
    }
  });
  const applyWithResumeMutation = useMutation({
    mutationFn: () =>
      applicationApi.create({
        internshipId: internship._id,
        status: "APPLIED",
        notes: "Applied with the tailored resume version generated by CareerPilot."
      }),
    onSuccess: () => {
      setApplicationNotice("Applied with your updated resume and saved to Tracker.");
      queryClient.invalidateQueries({ queryKey: ["applications"] });
      queryClient.invalidateQueries({ queryKey: ["analytics"] });
      queryClient.invalidateQueries({ queryKey: ["notifications"] });
    }
  });

  if (internshipsQuery.isLoading) return <LoadingState label="Loading opportunity" />;
  if (!internship) {
    return (
      <div className="rounded-lg border border-ink/10 bg-white p-6 shadow-soft">
        <p className="font-bold text-ink">Internship not found.</p>
        <Link className="mt-3 inline-block font-black text-moss" to="/internships">
          Back to explorer
        </Link>
      </div>
    );
  }

  const skillGap = skillGapQuery.data?.skillGap;
  const openApplyLink = (externalWindow) => {
    if (externalWindow) {
      externalWindow.opener = null;
      externalWindow.location.href = internship.applyLink;
    } else {
      window.open(internship.applyLink, "_blank", "noopener,noreferrer");
    }
  };
  const handleExternalApply = async () => {
    const externalWindow = window.open("about:blank", "_blank");
    try {
      await externalApplyMutation.mutateAsync();
      openApplyLink(externalWindow);
    } catch (error) {
      if (externalWindow) externalWindow.close();
    }
  };
  const handleApplyWithResume = async () => {
    const externalWindow = window.open("about:blank", "_blank");
    try {
      await applyWithResumeMutation.mutateAsync();
      openApplyLink(externalWindow);
    } catch (error) {
      if (externalWindow) externalWindow.close();
    }
  };
  const handleViewPdf = async () => {
    if (!resumeVersion?._id) return;
    setPdfLoading(true);
    setPdfError("");
    try {
      await materialApi.openPdf(resumeVersion._id);
    } catch (error) {
      setPdfError("Could not open the resume PDF. Please try again.");
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
      <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft">
        <ErrorBanner
          error={
            materialMutation.error ||
            approveMutation.error ||
            applicationMutation.error ||
            externalApplyMutation.error ||
            applyWithResumeMutation.error ||
            skillGapQuery.error
          }
        />
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <p className="text-sm font-black uppercase tracking-[0.16em] text-gold">{internship.source}</p>
            <h2 className="mt-2 text-3xl font-black text-ink">{internship.title}</h2>
            <p className="mt-1 text-base font-semibold text-ink/55">
              {internship.company} - {internship.location}
            </p>
          </div>
          <div className="grid h-20 w-24 place-items-center rounded-md bg-moss/10 text-3xl font-black text-moss">
            {internship.match?.score || 0}%
          </div>
        </div>

        <p className="mt-5 text-sm font-medium leading-7 text-ink/70">{internship.description}</p>
        <div className="mt-5 flex flex-wrap gap-2">
          {internship.skillsRequired?.map((skill) => (
            <span key={skill} className="rounded-full bg-ink/5 px-3 py-1 text-xs font-black text-ink/65">
              {skill}
            </span>
          ))}
        </div>
        <div className="mt-5 grid gap-3 rounded-md bg-paper p-4 text-sm font-semibold text-ink/65 sm:grid-cols-2">
          <p>Deadline: {formatDate(internship.deadline)}</p>
          <p>Posted: {formatDate(internship.postedDate)}</p>
        </div>

        {internship.match ? (
          <div className="mt-6 grid gap-4 md:grid-cols-2">
            <MatchBox title="Matched Skills" items={internship.match.matchedSkills} tone="moss" />
            <MatchBox title="Missing Skills" items={internship.match.missingSkills} tone="coral" />
          </div>
        ) : null}
        {internship.match?.reason ? (
          <div className="mt-5 rounded-md border border-moss/20 bg-moss/5 p-4 text-sm font-semibold leading-6 text-ink/70">
            {internship.match.reason}
          </div>
        ) : null}

        <div className="mt-6 flex flex-wrap gap-2">
          <Button
            icon={Plus}
            variant="secondary"
            loading={applicationMutation.isPending}
            onClick={() => applicationMutation.mutate({ internshipId: internship._id, status: "SAVED" })}
          >
            Save to Tracker
          </Button>
          <Button icon={FileText} loading={materialMutation.isPending} onClick={() => materialMutation.mutate(internship._id)}>
            Generate Resume Version
          </Button>
          <Button
            icon={ExternalLink}
            loading={externalApplyMutation.isPending}
            onClick={handleExternalApply}
          >
            Apply Externally
          </Button>
        </div>
        {applicationNotice ? (
          <p className="mt-4 inline-flex items-center gap-2 rounded-md bg-moss/10 px-3 py-2 text-sm font-black text-moss">
            <CheckCircle2 className="h-4 w-4" />
            {applicationNotice}
          </p>
        ) : null}
      </section>

      <aside className="grid gap-6">
        <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft">
          <h3 className="text-xl font-black text-ink">Skill Gaps</h3>
          <div className="mt-4 grid gap-3">
            {skillGap?.priorities?.length ? (
              skillGap.priorities.map((item) => (
                <div key={item.skill} className="rounded-md bg-paper p-4">
                  <div className="flex items-center justify-between gap-3">
                    <p className="font-black text-ink">{item.skill}</p>
                    <span className="rounded-full bg-gold/15 px-2.5 py-1 text-xs font-black text-gold">{item.priority}</span>
                  </div>
                  <p className="mt-2 text-sm font-semibold text-ink/60">{item.suggestedAction}</p>
                  <p className="mt-2 text-sm font-semibold text-moss">{item.miniProject}</p>
                </div>
              ))
            ) : (
              <p className="text-sm font-semibold text-ink/55">Generate matches to view ranked gaps.</p>
            )}
          </div>
        </section>

        <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft">
          <div className="flex items-center justify-between gap-3">
            <h3 className="text-xl font-black text-ink">Resume Version</h3>
            {resumeVersion?.approved ? (
              <span className="rounded-full bg-moss/10 px-3 py-1 text-xs font-black text-moss">Approved</span>
            ) : null}
          </div>
          {resumeVersion ? (
            <div className="mt-4 grid gap-4">
              <ul className="grid gap-2 text-sm font-semibold text-ink/65">
                {resumeVersion.changeSummary?.map((item) => (
                  <li key={item} className="flex gap-2">
                    <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-gold" />
                    {item}
                  </li>
                ))}
              </ul>
              <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-md bg-ink p-4 text-sm leading-6 text-white scrollbar-thin">
                {resumeVersion.content}
              </pre>
              <div className="flex flex-wrap gap-2">
                <Button icon={Download} variant="secondary" loading={pdfLoading} onClick={handleViewPdf}>
                  View PDF
                </Button>
                {!resumeVersion.approved ? (
                  <Button icon={Check} loading={approveMutation.isPending} onClick={() => approveMutation.mutate(resumeVersion._id)}>
                    Approve Version
                  </Button>
                ) : null}
              </div>
              {pdfError ? <p className="text-sm font-bold text-coral">{pdfError}</p> : null}
              <div className="rounded-md border border-moss/20 bg-moss/5 p-4">
                <p className="text-sm font-black text-ink">Apply with updated resume</p>
                <p className="mt-1 text-sm font-semibold text-ink/60">
                  Submit to {internship.company} using the tailored version above. The PDF opens for your records and the
                  application is logged in the Tracker as Applied.
                </p>
                <div className="mt-3 flex flex-wrap gap-2">
                  <Button icon={Download} variant="secondary" loading={pdfLoading} onClick={handleViewPdf}>
                    Download PDF
                  </Button>
                  <Button icon={Send} loading={applyWithResumeMutation.isPending} onClick={handleApplyWithResume}>
                    Apply With Updated Resume
                  </Button>
                </div>
              </div>
            </div>
          ) : (
            <p className="mt-4 text-sm font-semibold text-ink/55">
              No generated version for this internship yet. Use Generate Resume Version to tailor your resume to this role.
            </p>
          )}
        </section>
      </aside>
    </div>
  );
}

function MatchBox({ title, items = [], tone }) {
  const color = tone === "moss" ? "bg-moss/10 text-moss" : "bg-coral/10 text-coral";
  return (
    <div className="rounded-md bg-paper p-4">
      <h3 className="text-sm font-black uppercase tracking-[0.16em] text-ink/45">{title}</h3>
      <div className="mt-3 flex flex-wrap gap-2">
        {items.length ? (
          items.map((item) => (
            <span key={item} className={`rounded-full px-3 py-1 text-xs font-black ${color}`}>
              {item}
            </span>
          ))
        ) : (
          <span className="text-sm font-semibold text-ink/50">None</span>
        )}
      </div>
    </div>
  );
}
